# Generated by Django 4.2.7 on 2023-12-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_todotable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotable',
            name='checked',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todotable',
            name='content',
            field=models.TextField(max_length=50),
        ),
    ]
