# Generated by Django 4.2.7 on 2023-12-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_alter_todotable_checked_alter_todotable_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotable',
            old_name='checked',
            new_name='field_id',
        ),
    ]
