# Generated by Django 4.2.7 on 2023-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_rename_checked_todotable_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotable',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
