# Generated by Django 4.2.2 on 2023-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_alter_todotable_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotable',
            name='field_id',
        ),
        migrations.AlterField(
            model_name='todotable',
            name='checked',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='todotable',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
